### ISSUE TITLE
Chapter 13's use of PySimpleGUI

### ISSUE THREAD

**Issue by PySimpleGUI** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#1]
Hi there.... was going to try and ask this question privately but couldn't find a way to directly reach the Brian.

Wondering what drove the decision to use PySimpleGUI as your GUI in Chapter 13 and if it's used elsewhere as well.  Are there other projects you've used PySimpleGUI on before or since this book?  Any comments on your experiences?

**Comment by brian-amos-embedded** [comment]
hehe "the Brian" . . . I think I'm more of "a Brian"  :-)  

No worries on the public comment/question, I'm happy to answer!  Also, feel free to email me directly: brianamos@holisticembedded.com

I chose PySimpleGUI because: 
* My readers are likely coming from a programming background in C (not python) and likely have no GUI development experience.  Using a complex GUI framework requiring lots of code would have added no value to the example.  It also would have made the code much less approachable and drawn the focus to the bulk of code that was driving the GUI, rather than code pertinent to communicating with the microcontroller.
* I wanted to eliminate external dependencies that needed to be installed outside of a simple `pip install -r `
* The example code needed run across multiple platforms (windows, linux, macOS)
* I needed something easy for me to use (I'm an embedded developer who deals with real-time systems) - I don't spend much time dabbling in UIs.

In the past I've used PySimpleGUI to create some straight forward UIs that were test harnesses for embedded systems.  It is perfect for quickly/easily whipping up a functional UI when you don't necessarily want to tinker with every visual element.  Combined with Python, PySimpleGUI provides a fast and efficient PC-based front end for an embedded device.

Chapter 13 is the only place where python is used in this book ( Segger Ozone and Segger SystemView are used to visualize code examples elsewhere).  However, anytime I need a front end for a Python script, PySimpleGUI is my first stop!

Thanks for all of your work in creating PySimpleGUI and the wealth of documentation - especially the examples!
