### ISSUE TITLE
Issues running examples under Linux

### ISSUE THREAD

**Issue by G4DCP** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#2]
I'm having problems with the Chapter5_6.jdebug file.

Apart from the paths all referencing the Windows AC6 ide rather than being suitble for CubeIDE on Linux I have a problem with the AfterTargetReset script. It uses ELV-GetBaseAddr which is returning 0x8000 and everything falls apart!

Advice please

I can't see that the link has linked to the right addresses.

--
Peter G4DCP

**Comment by G4DCP** [comment]
The cubeIDE was not picking up the linker script.

So this can be closed, was this tested on linux or should I be using the Windows versions

**Comment by brian-amos-embedded** [comment]
Hi Peter, 

The examples were developed and tested under windows.  In theory, STM32CubeIDE, SystemView, and Ozone are all cross-platform programs, but I didn't explicitly test multiple platforms. 

The earlier chapters were developed using Atollic TrueSTUDIO (before STM announced that it shouldn't be used for new projects) .  These project files were converted to CubeIDE.  There were some problems migrating the projects (specifically chapters 5 & 6), but they should be cleared up now.  

AC6 wasn't used, so I'm no sure why paths would reference anything from them ( but seeing an Atollic TrudSTUDIO path wouldn't surprise me).

Also, releases of the examples before [04cf5ec](https://github.com/PacktPublishing/Hands-On-RTOS-with-Microcontrollers/commit/04cf5ecd88b110388f6f166485dddb8f39d0f5b5) had resources specified with absolute paths, but that was fixed a few weeks ago.

Did you resolve your linker issues or move to Windows?

**Comment by G4DCP** [comment]
Yes,

I resolved the issue by opening the properties and changing the linker script to point at the correct linker script.

There are a number of issues that I can tell you about if you wish, most can be worked around and so far I have done that.

I am only at chapter 8 but if you want I can keep notes of the issues on linux and forward them to you. I have a few for chapters 5-7 what email adress should I forward them to?

When you fixed the absolute paths did you do the Ozone configs as those in chps 6 and 7 have hard coded windows paths in them!

Many thanks for the reply.

My reference to AC6 should probably have been to atollic I noticed them and replaced them with paths that worked for me.

I also note that chapter 7 [main_taskCreation.c] was missing the SEGGER_SYSVIEW_Conf(); call which made getting a capture with SystemView interesting!

----
Peter
G4DCP retired Mainframe Software Expert



--

**Comment by brian-amos-embedded** [comment]
Thanks for the detailed list Peter!

You can either forward issues directly to me - brianamos@holisticembedded.com and I'll create new issues here or you're welcome to enter them directly in the issue tracker here.  Whichever is easiest for you works for me, I appreciate the feedback.

Concerning Ozone: From what I've seen, each time a data file (like *.elf) is opened Ozone repopulates the paths with absolute paths.  Since each **_*.jdebug_** config file is used multiple times throughout a chapter, the intent is that you'll use File-->Open to select the Ozone config file and get an error when attempting to open *.elf:
![image](https://user-images.githubusercontent.com/12746706/87535680-dc67ad00-c665-11ea-8710-ae5ef842e952.png)

After the ozone config file is loaded, you can load in whichever *.elf file you're interested in with the File-->Open.
