### ISSUE TITLE
Chapter 14 warnings

### ISSUE THREAD

**Issue by brian-amos-embedded** [PacktPublishing/Hands-On-RTOS-with-Microcontrollers#5]
Chapter 14 throws several warnings.

**Comment by dsjwork** [comment]
Hi Brian,

The current git clone for this project fails its build because of various include headers files that cannot be found for project Chapter5_6. The other chapters build OK. On further investigation, it appears that the list of include file paths for this project needs to be updated to those of the other chapters. I simply copied the list from C/C++|Build|Settings|Tool Settings|MCU GCC Compiler|Include paths for Chapter_9 to Chapter5_6 etc. This resolved the issue.

Congratulations an an excellent book and debug environment. I have changed over to the Segger way of doing things for FreeRTOS work after reading your book.

Regards
Dave Jones
